"""
Comment Remover for JSON Blueprint Files
Removes all Python comments (# and docstrings) from the 'content' fields
in JSON blueprint files generated by blueprint_builder.py
"""
import json
import re


def remove_inline_comments(code: str) -> str:
    """
    Remove inline # comments from code lines.
    Preserves # characters inside strings.
    
    Args:
        code: Python code string
        
    Returns:
        Code with inline comments removed
    """
    lines = code.split('\n')
    cleaned_lines = []
    
    for line in lines:
        # Skip lines that are purely comments
        if line.strip().startswith('#'):
            continue
            
        # Remove inline comments (after code)
        if '#' in line:
            # Simple approach: split by # and take first part
            # This doesn't handle # inside strings perfectly, but works for most cases
            code_part = line.split('#')[0].rstrip()
            if code_part:  # Only keep if there's actual code
                cleaned_lines.append(code_part)
        else:
            cleaned_lines.append(line)
    
    return '\n'.join(cleaned_lines)


def remove_docstrings(code: str) -> str:
    """
    Remove docstrings (triple-quoted strings) from code.
    Handles both ''' and \"\"\" style docstrings.
    
    Args:
        code: Python code string
        
    Returns:
        Code with docstrings removed
    """
    lines = code.split('\n')
    cleaned_lines = []
    in_docstring = False
    docstring_delimiter = None
    skip_next_empty_lines = False
    
    for line in lines:
        stripped = line.strip()
        
        # Check if we're entering a docstring
        if not in_docstring:
            if stripped.startswith('"""') or stripped.startswith("'''"):
                docstring_delimiter = stripped[:3]
                
                # Check if it's a single-line docstring
                if len(stripped) > 3 and stripped.endswith(docstring_delimiter):
                    # Single line docstring, skip it
                    skip_next_empty_lines = True
                    continue
                elif stripped.count(docstring_delimiter) >= 2:
                    # Single line docstring
                    skip_next_empty_lines = True
                    continue
                else:
                    # Multi-line docstring starts
                    in_docstring = True
                    continue
            else:
                # Not a docstring, keep the line
                if skip_next_empty_lines and stripped == '':
                    continue
                skip_next_empty_lines = False
                cleaned_lines.append(line)
        else:
            # We're inside a docstring, look for the closing delimiter
            if docstring_delimiter in stripped:
                # Found closing delimiter
                in_docstring = False
                docstring_delimiter = None
                skip_next_empty_lines = True
            # Skip this line (it's part of the docstring)
            continue
    
    return '\n'.join(cleaned_lines)


def clean_code_content(code: str) -> str:
    """
    Remove all comments and docstrings from Python code.
    
    Args:
        code: Python code string
        
    Returns:
        Cleaned code without comments or docstrings
    """
    # First remove docstrings
    code = remove_docstrings(code)
    
    # Then remove inline comments
    code = remove_inline_comments(code)
    
    # Clean up excessive blank lines (more than 2 consecutive)
    code = re.sub(r'\n{3,}', '\n\n', code)
    
    return code


def process_blueprint_json(input_file: str, output_file: str) -> None:
    """
    Process a blueprint JSON file and remove all comments from 'content' fields.
    
    Args:
        input_file: Path to input JSON file
        output_file: Path to output JSON file
    """
    print(f"Reading {input_file}...")
    
    with open(input_file, 'r', encoding='utf-8') as f:
        blueprint = json.load(f)
    
    # Track statistics
    total_actions = len(blueprint.get('actions', []))
    modified_count = 0
    
    print(f"Processing {total_actions} actions...")
    
    # Process each action
    for action in blueprint.get('actions', []):
        if action.get('type') == 'writeText' and 'content' in action:
            original_content = action['content']
            cleaned_content = clean_code_content(original_content)
            
            if cleaned_content != original_content:
                action['content'] = cleaned_content
                modified_count += 1
    
    print(f"Modified {modified_count} writeText actions")
    print(f"Saving to {output_file}...")
    
    with open(output_file, 'w', encoding='utf-8') as f:
        json.dump(blueprint, f, indent=2, ensure_ascii=False)
    
    print(f"✓ Done! Clean blueprint saved to {output_file}")


if __name__ == '__main__':
    input_path = '/Volumes/hard-drive/auto-write-vs-code/json-project-builder/blueprint-generator/andrej-kara-nunuchat.json'
    output_path = '/Volumes/hard-drive/auto-write-vs-code/json-project-builder/blueprint-generator/andrej-kara-nunuchat-clean.json'
    
    process_blueprint_json(input_path, output_path)
